### ISSUE TITLE
Error for `cargo-audit`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [taiki-e/cache-cargo-install-action#2]
I'm getting an error when trying to use the action for `cargo-audit` see https://github.com/JonathanWoollett-Light/clippy-tracing/actions/runs/5891625757/job/15979081250?pr=9

**Comment by taiki-e** [comment]
This is https://github.com/rust-lang/rust/issues/113152. Try `locked: false` inout option.

**Comment by taiki-e** [comment]
Alternatively, you can use cache-cargo-install-action before running `rustup default nightly` to avoid the nightly compiler.
