### ISSUE TITLE
Node.js 16 actions are deprecated.  Please update actions/cache to v4

### ISSUE THREAD

**Issue by elibroftw** [taiki-e/cache-cargo-install-action#5]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

https://github.com/taiki-e/cache-cargo-install-action/blob/e57d133d3c2bc6196d57ce056266ea53dd4feb6d/action.yml#L43

**Comment by taiki-e** [comment]
This is discussed in https://github.com/taiki-e/cache-cargo-install-action/pull/3. See https://github.com/taiki-e/cache-cargo-install-action/pull/3#issuecomment-1987491814 for a detailed explanation.

**Comment by taiki-e** [comment]
Addressed in 2.0.0.
