### ISSUE TITLE
Incorrect cache branch handling when using a workflow triggered by a tag

### ISSUE THREAD

**Issue by Enduriel** [taiki-e/cache-cargo-install-action#6]
I suspect this issue is caused by the behavior described [here](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key) as well as the fact that the workflow 'branch' for workflows triggered by
```yml
on:
  push:
    tags:
      - '*.*.*'
```
is the tag, rather than the branch. This means if I run my workflow first on 0.1.0, and then on 0.1.1, the cache will not be used because the cache was stored on the 0.1.0 'branch' as far as the github action is concerned.

I don't have enough experience with github actions to be able to make a PR to fix this myself (couldn't find the relevant code for the cleanup part of the action), but I know this should be possible because [Swatinem/rust-cache](https://github.com/Swatinem/rust-cache) doesn't have this issue.

You can see the issue in the cache for my project [here](https://github.com/MSUTeam/MSU-Launcher/actions/caches)

**Comment by NobodyXu** [comment]
> is the tag, rather than the branch. This means if I run my workflow first on 0.1.0, and then on 0.1.1

It's a restriction imposed by GitHub, you could only reuse cache from the base branch and the current branch.

**Comment by Enduriel** [comment]
Is there no way to push the cache to a more 'global' scope?

**Comment by taiki-e** [comment]
> [Swatinem/rust-cache](https://github.com/Swatinem/rust-cache) doesn't have this issue.

From the list of caches you linked to, I see that the rust-cache's cache was created in the main branch. So I think that it does not meet the conditions that would cause the same problem.

**Comment by Enduriel** [comment]
Ah, you're right, because I run the rust cache even for my CI, whereas the install cache is only done during the build. Seems like the best solution is for me to build on every commit... I guess that's *a* solution, thanks for your time and sorry for the confusion
